import Link from "next/link";
import { requireStaffRole } from "@/lib/auth/authorization";
import { OwnerOperationsShell } from "../_components/portal-shells";

export default async function VerificationQueue() {
  const { supabase, user } = await requireStaffRole(["super_admin", "verification_reviewer"]);
  const { data: requests } = await supabase.from("ap_verifications").select("id,agency_id,status,submitted_at,ap_agencies(name,country)").in("status", ["pending", "needs_information"]).order("submitted_at", { ascending: true });
  return <OwnerOperationsShell active="verification" email={user.email}><main className="ops-main"><header className="ops-header"><div><p className="ops-kicker">INDEPENDENT TRUST REVIEW</p><h1>Verification queue.</h1><p>Review private business evidence independently from billing, visibility, ranking, and publication decisions.</p></div><div className="ops-summary"><span>REQUESTS WAITING</span><strong>{requests?.length ?? 0}</strong><small>Evidence review required</small></div></header><div className="ops-toolbar"><span>Secure evidence is visible only to authorized reviewers</span><Link href="/owners/dashboard">RETURN TO OVERVIEW</Link></div><section className="ops-grid">{requests?.length ? requests.map((request) => { const agency = Array.isArray(request.ap_agencies) ? request.ap_agencies[0] : request.ap_agencies; return <article className="ops-card" key={request.id}><div className="ops-card-top"><span className="ops-badge">{request.status.replace("_", " ")}</span><span className="ops-card-id">{request.id.slice(0, 8)}</span></div><h2>{agency?.name ?? "Agency"}</h2><p>{agency?.country ?? "Country not provided"}</p><div className="ops-card-footer"><small>{request.submitted_at ? new Date(request.submitted_at).toLocaleDateString("en-PH") : "Submission date unavailable"}</small><Link className="ops-action" href={`/owners/dashboard/verifications/${request.id}`}>REVIEW EVIDENCE →</Link></div></article>; }) : <div className="ops-empty"><strong>Verification is clear.</strong><span>No business-evidence requests are currently awaiting independent review.</span></div>}</section></main></OwnerOperationsShell>;
}
