import Link from "next/link";
import { notFound } from "next/navigation";
import { requireStaffRole } from "@/lib/auth/authorization";
import { OwnerOperationsShell } from "../../_components/portal-shells";
import { CaseHistory } from "../../_components/case-history";
import { resolveFraudInvestigation } from "../actions";

export default async function FraudInvestigation({params,searchParams}:{params:Promise<{investigationId:string}>;searchParams:Promise<Record<string,string|undefined>>}){const {investigationId}=await params;const query=await searchParams;const {supabase,user}=await requireStaffRole(["super_admin","moderator","verification_reviewer"]);const {data:item}=await supabase.from("ap_fraud_investigations").select("*,ap_agencies(name)").eq("id",investigationId).maybeSingle();if(!item)notFound();const {data:history}=await supabase.from("ap_security_audit").select("id,action,actor_user_id,metadata,created_at").eq("target_id",investigationId).order("created_at");const agency=Array.isArray(item.ap_agencies)?item.ap_agencies[0]:item.ap_agencies;const open=["open","investigating"].includes(item.status);
return <OwnerOperationsShell active="fraud" email={user.email}><main className="case-main"><nav className="workflow-breadcrumb"><Link href="/owners/dashboard/fraud">FRAUD REVIEW</Link><span>/</span><b>INVESTIGATION</b></nav><header className="case-header"><div><p>{item.severity.toUpperCase()} RISK · {item.signal_type.replaceAll("_"," ").toUpperCase()}</p><h1>{agency?.name??"Integrity investigation"}</h1><span>Automated signals are indicators only. Review the underlying record and evidence before recording an outcome.</span></div><div><small>INVESTIGATION ID</small><b>{investigationId.slice(0,8).toUpperCase()}</b><span className={open?"open":"resolved"}>{item.status.toUpperCase()}</span></div></header>{query.error&&<p className="profile-flash error" role="alert">{query.error}</p>}{query.reviewed&&<p className="profile-flash" role="status">Investigation status recorded: {query.reviewed}.</p>}
<div className="case-layout"><div><section className="case-evidence"><div className="case-section-head"><p>RISK ASSESSMENT</p><h2>Investigation record</h2></div><dl><div><dt>SIGNAL</dt><dd>{item.summary}</dd></div><div><dt>SEVERITY</dt><dd>{item.severity.toUpperCase()}</dd></div><div><dt>SOURCE TARGET</dt><dd>{item.target_type.toUpperCase()} · {item.target_id}</dd></div><div><dt>SUBJECT ACCOUNT</dt><dd>{item.subject_user_id??"No account attached"}</dd></div><div><dt>DETECTION DATA</dt><dd><pre>{JSON.stringify(item.signals??{},null,2)}</pre></dd></div>{item.resolution&&<div><dt>RESOLUTION</dt><dd>{item.resolution}</dd></div>}</dl></section><CaseHistory events={history??[]} openedAt={item.created_at} openedLabel="fraud investigation opened"/></div><aside>{open?<section className="case-actions"><p>HUMAN REVIEW</p><h2>Record an outcome</h2><FraudForm id={investigationId} decision="investigating" label="MARK INVESTIGATING"/><FraudForm id={investigationId} decision="cleared" label="CLEAR SIGNAL"/><FraudForm id={investigationId} decision="confirmed" label="CONFIRM FRAUD" danger/></section>:<section className="case-closed"><span>✓</span><h2>Investigation resolved</h2><p>The result and reviewer rationale are preserved in the audit record.</p></section>}</aside></div></main></OwnerOperationsShell>}
function FraudForm({id,decision,label,danger=false}:{id:string;decision:"investigating"|"cleared"|"confirmed";label:string;danger?:boolean}){return <form action={resolveFraudInvestigation.bind(null,id,decision)}><label><span>REVIEWER RATIONALE</span><textarea name="reason" minLength={20} required placeholder="Record evidence reviewed and why this outcome is appropriate."/></label><button className={danger?"danger":undefined}>{label}<b>→</b></button></form>}
