/* eslint-disable @next/next/no-img-element */
import { saveEditorialPost } from "./actions";

export type EditorialPost = { id:string; title:string; slug:string; content_type:string; category:string; summary:string; body:string; tags:string[]; author_name:string; cover_image_url:string|null; cover_image_alt:string|null; seo_title:string; seo_description:string; canonical_url:string|null; status:string; commercial_disclosure:string|null; publish_at:string|null };
const types = [["article","Article"],["visual_editorial","Visual editorial"],["agency_spotlight","Agency spotlight"],["prive_report","Privé report"],["market_graphic","Market/data graphic"],["interview","Interview"],["editorial_case_study","Editorial case study"]];
const categories = ["creator-economy","agencies","business","influence","entertainment","culture","adult-industry","interviews","market-insights"];
export function EditorialForm({ post }: { post?: EditorialPost }) {
  return <form className="editorial-form" action={saveEditorialPost.bind(null,post?.id ?? null)} encType="multipart/form-data">
    <section><div className="editorial-section-title"><span>01</span><div><p>STORY FOUNDATION</p><h2>Editorial identity</h2></div></div><div className="editorial-fields"><label className="wide">Title<input name="title" defaultValue={post?.title} minLength={8} maxLength={180} required /></label><label>Stable URL slug<input name="slug" defaultValue={post?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="future-of-creator-agencies" required /></label><label>Content format<select name="content_type" defaultValue={post?.content_type ?? "article"}>{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Category<select name="category" defaultValue={post?.category ?? "agencies"}>{categories.map(x=><option value={x} key={x}>{x.replaceAll("-"," ")}</option>)}</select></label><label>Author / editor<input name="author_name" defaultValue={post?.author_name} required /></label><label className="wide">Description / standfirst<textarea name="summary" defaultValue={post?.summary} minLength={30} maxLength={500} required /></label><label className="wide">Tags, comma-separated<input name="tags" defaultValue={post?.tags?.join(", ")} /></label></div></section>
    <section><div className="editorial-section-title"><span>02</span><div><p>VISUAL &amp; BODY</p><h2>Publication content</h2></div></div><div className="editorial-fields"><input type="hidden" name="existing_cover_url" value={post?.cover_image_url ?? ""} /><label>Cover / graphic<input name="cover_image" type="file" accept="image/jpeg,image/png,image/webp,image/gif" /></label><label>Image alt description<input name="cover_image_alt" defaultValue={post?.cover_image_alt ?? ""} placeholder="Describe the image for accessibility" /></label>{post?.cover_image_url && <div className="editorial-cover-preview wide"><img src={post.cover_image_url} alt={post.cover_image_alt ?? "Current cover"} /></div>}<label className="wide">Article body<textarea className="editorial-body" name="body" defaultValue={post?.body} minLength={100} required placeholder="Write the complete article. Separate paragraphs with a blank line." /></label><label className="wide">Commercial disclosure<input name="commercial_disclosure" defaultValue={post?.commercial_disclosure ?? ""} placeholder="Leave blank for independent editorial; disclose Sponsored or Partner Content here." /></label></div></section>
    <section><div className="editorial-section-title"><span>03</span><div><p>DISCOVERY</p><h2>SEO and distribution</h2></div></div><div className="editorial-fields"><label className="wide">SEO title<input name="seo_title" defaultValue={post?.seo_title} maxLength={70} required /></label><label className="wide">SEO description<textarea name="seo_description" defaultValue={post?.seo_description} minLength={50} maxLength={180} required /></label><label className="wide">Canonical URL<input name="canonical_url" type="url" defaultValue={post?.canonical_url ?? ""} placeholder="Optional external canonical URL" /></label></div></section>
    <section><div className="editorial-section-title"><span>04</span><div><p>WORKFLOW</p><h2>Review and release</h2></div></div><div className="editorial-fields"><label>Status<select name="status" defaultValue={post?.status ?? "draft"}>{["draft","in_review","scheduled","published","archived"].map(x=><option value={x} key={x}>{x.replace("_"," ")}</option>)}</select></label><label>Publish date and time<input name="publish_at" type="datetime-local" defaultValue={post?.publish_at?.slice(0,16) ?? ""} /></label><div className="editorial-safety wide"><b>Publication check</b><span>Confirm sourcing, rights, disclosures, privacy, and editorial review before selecting Published. Scheduled posts become publicly readable only after their release time.</span></div><button className="wide">SAVE EDITORIAL POST <span>→</span></button></div></section>
  </form>;
}
