import Link from "next/link";
import { notFound } from "next/navigation";
import { requireStaffRole } from "@/lib/auth/authorization";
import { OwnerOperationsShell } from "../../_components/portal-shells";
import { CaseHistory } from "../../_components/case-history";
import { updatePlacementStatus } from "../actions";

export default async function PlacementDetail({params,searchParams}:{params:Promise<{placementId:string}>;searchParams:Promise<Record<string,string|undefined>>}){const {placementId}=await params;const query=await searchParams;const {supabase,user}=await requireStaffRole(["super_admin","finance"]);const {data:item}=await supabase.from("ap_sponsored_placements").select("*,ap_agencies(name,country,publication_status,published)").eq("id",placementId).maybeSingle();if(!item)notFound();const {data:history}=await supabase.from("ap_security_audit").select("id,action,actor_user_id,metadata,created_at").eq("target_id",placementId).order("created_at");const agency=Array.isArray(item.ap_agencies)?item.ap_agencies[0]:item.ap_agencies;
return <OwnerOperationsShell active="placements" email={user.email}><main className="case-main"><nav className="workflow-breadcrumb"><Link href="/owners/dashboard/placements">SPONSORED PLACEMENTS</Link><span>/</span><b>PLACEMENT RECORD</b></nav><header className="case-header"><div><p>FEATURED / SPONSORED</p><h1>{agency?.name??"Commercial placement"}</h1><span>Manage the campaign state and disclosure record without affecting the agency’s independent trust status.</span></div><div><small>PLACEMENT ID</small><b>{placementId.slice(0,8).toUpperCase()}</b><span className={item.status==="active"?"resolved":"open"}>{item.status.toUpperCase()}</span></div></header>{query.error&&<p className="profile-flash error">{query.error}</p>}{query.updated&&<p className="profile-flash">Placement status updated to {query.updated}.</p>}<div className="case-layout"><div><section className="case-evidence"><div className="case-section-head"><p>COMMERCIAL RECORD</p><h2>Placement details</h2></div><dl><div><dt>DISCLOSURE</dt><dd><b>{item.disclosure_label}</b></dd></div><div><dt>INVENTORY</dt><dd>{item.placement_type}{item.placement_key?` / ${item.placement_key}`:""}</dd></div><div><dt>CAMPAIGN WINDOW</dt><dd>{new Date(item.starts_at).toLocaleString("en-PH")} — {new Date(item.ends_at).toLocaleString("en-PH")}</dd></div><div><dt>COMMERCIAL REFERENCE</dt><dd>{item.commercial_reference||"Not provided"}</dd></div><div><dt>INTERNAL NOTES</dt><dd>{item.internal_notes||"Not provided"}</dd></div><div><dt>TRUST SEPARATION</dt><dd>Profile: {agency?.publication_status}; publicly visible: {agency?.published?"yes":"no"}. Placement does not change verification or ranking.</dd></div></dl></section><CaseHistory events={history??[]} openedAt={item.created_at} openedLabel="placement created"/></div><aside><section className="case-actions"><p>PLACEMENT CONTROL</p><h2>Change campaign state</h2>{item.status!=="active"&&<PlacementForm id={placementId} status="active" label="ACTIVATE PLACEMENT"/>}{item.status!=="paused"&&<PlacementForm id={placementId} status="paused" label="PAUSE PLACEMENT"/>}{!['expired','cancelled'].includes(item.status)&&<PlacementForm id={placementId} status="cancelled" label="CANCEL PLACEMENT" danger/>}</section></aside></div></main></OwnerOperationsShell>}
function PlacementForm({id,status,label,danger=false}:{id:string;status:"active"|"paused"|"cancelled";label:string;danger?:boolean}){return <form action={updatePlacementStatus.bind(null,id,status)}><label><span>STATUS-CHANGE REASON</span><textarea name="reason" minLength={10} required placeholder="Record why this placement status is changing."/></label><button className={danger?"danger":undefined}>{label}<b>→</b></button></form>}
