import { requireStaffRole } from "@/lib/auth/authorization";
import { OwnerOperationsShell } from "../_components/portal-shells";
import { updateInquiry } from "./actions";
type Inquiry = { id:string; sender_name:string; sender_email:string; message:string; source:string; status:string; qualification_status:string; created_at:string; ap_agencies:{name:string}|{name:string}[]|null };
export default async function InquiryOperationsPage({ searchParams }: { searchParams: Promise<{ updated?: string; error?: string }> }) {
  const { supabase, user } = await requireStaffRole(["super_admin", "support"]); const params = await searchParams;
  const { data } = await supabase.from("ap_inquiries").select("id,sender_name,sender_email,message,source,status,qualification_status,created_at,ap_agencies(name)").order("created_at", { ascending: false }).limit(100); const inquiries = (data ?? []) as Inquiry[];
  return <OwnerOperationsShell active="inquiries" email={user.email}><main className="inquiry-main"><section className="inquiry-hero"><div><p className="eyebrow">MARKETPLACE DEMAND</p><h1>Inquiry operations.</h1><p>Review lead quality, record acceptance outcomes, and keep every classification attributable.</p></div><div><b>{inquiries.length}</b><span>RECENT INQUIRIES</span></div></section>{params.updated && <p className="operation-notice">Inquiry decision recorded.</p>}{params.error && <p className="operation-error">{params.error}</p>}<section className="inquiry-list">{inquiries.length ? inquiries.map((item) => { const agency=Array.isArray(item.ap_agencies)?item.ap_agencies[0]:item.ap_agencies; return <article key={item.id}><header><div><p>{item.source.toUpperCase()} · {new Intl.DateTimeFormat("en-PH",{dateStyle:"medium"}).format(new Date(item.created_at))}</p><h2>{agency?.name ?? "Agency inquiry"}</h2></div><span>{item.qualification_status.replace("_"," ")}</span></header><div className="inquiry-contact"><p><b>{item.sender_name}</b><a href={`mailto:${item.sender_email}`}>{item.sender_email}</a></p><p>{item.message}</p></div><form action={updateInquiry.bind(null,item.id)}><label>Status<select name="status" defaultValue={item.status}>{["new","delivered","accepted","declined","closed","spam"].map(x=><option key={x}>{x}</option>)}</select></label><label>Qualification<select name="qualification" defaultValue={item.qualification_status}>{["unreviewed","qualified","unqualified","fraud_flagged"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Decision note<textarea name="note" minLength={10} required placeholder="Record why this status and qualification were selected." /></label><button>RECORD DECISION</button></form></article>}) : <div className="analytics-empty">No inquiries have been submitted yet.</div>}</section></main></OwnerOperationsShell>;
}
