import Link from "next/link";
import { requireStaffRole } from "@/lib/auth/authorization";
import { OwnerOperationsShell } from "../_components/portal-shells";
import { createPlacement } from "./actions";

type Placement={id:string;placement_type:string;placement_key:string|null;disclosure_label:string;status:string;starts_at:string;ends_at:string;commercial_reference:string|null;ap_agencies:{name:string}|{name:string}[]|null};
export default async function PlacementManager({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const query=await searchParams;const {supabase,user}=await requireStaffRole(["super_admin","finance"]);const [{data:placements},{data:agencies}]=await Promise.all([supabase.from("ap_sponsored_placements").select("id,placement_type,placement_key,disclosure_label,status,starts_at,ends_at,commercial_reference,ap_agencies(name)").order("created_at",{ascending:false}),supabase.from("ap_agencies").select("id,name,country").eq("published",true).order("name")]);const rows=(placements??[]) as Placement[];const active=rows.filter(p=>p.status==="active"&&new Date(p.starts_at)<=new Date()&&new Date(p.ends_at)>new Date()).length;
return <OwnerOperationsShell active="placements" email={user.email}><main className="placement-main"><header className="ops-header"><div><p className="ops-kicker">COMMERCIAL VISIBILITY</p><h1>Sponsored placements.</h1><p>Schedule clearly disclosed paid visibility without changing verification, review outcomes, or objective ranking order.</p></div><div className="ops-summary"><span>ACTIVE PLACEMENTS</span><strong>{active}</strong><small>{rows.length} total records</small></div></header>{query.error&&<p className="profile-flash error">{query.error}</p>}{query.created&&<p className="profile-flash">Sponsored placement scheduled successfully.</p>}
<div className="placement-layout"><section className="placement-create"><div><p>NEW COMMERCIAL PLACEMENT</p><h2>Schedule inventory</h2><span>Only approved and published agencies are eligible. Every public appearance uses the disclosure “Featured / Sponsored.”</span></div><form action={createPlacement}><label className="wide"><span>AGENCY</span><select name="agency_id" required defaultValue=""><option value="" disabled>Select a published agency</option>{agencies?.map(a=><option value={a.id} key={a.id}>{a.name}{a.country?` — ${a.country}`:""}</option>)}</select></label><label><span>PLACEMENT TYPE</span><select name="placement_type" required defaultValue="directory"><option value="directory">Directory</option><option value="homepage">Homepage</option><option value="category">Category</option><option value="country">Country</option><option value="editorial">Editorial sponsorship</option></select></label><label><span>INVENTORY KEY</span><input name="placement_key" placeholder="Example: asia or homepage-primary"/></label><label><span>STARTS</span><input name="starts_at" type="datetime-local" required/></label><label><span>ENDS</span><input name="ends_at" type="datetime-local" required/></label><label><span>COMMERCIAL REFERENCE</span><input name="commercial_reference" placeholder="Invoice, contract, or campaign reference"/></label><label><span>INTERNAL NOTES</span><input name="internal_notes" placeholder="Private operations note"/></label><button className="wide">SCHEDULE PLACEMENT <b>→</b></button></form></section>
<aside className="placement-principles"><p>NON-NEGOTIABLE RULES</p><h2>Visibility is not trust.</h2><ol><li><span>01</span><div><b>Always disclosed</b><small>Paid inventory displays “Featured / Sponsored.”</small></div></li><li><span>02</span><div><b>No verified badge</b><small>Placement never creates or changes verification.</small></div></li><li><span>03</span><div><b>No ranking influence</b><small>Organic ranking order remains untouched.</small></div></li></ol></aside></div>
<section className="placement-list"><div className="placement-list-head"><div><p>INVENTORY RECORDS</p><h2>Placement schedule</h2></div><span>{rows.length} RECORDS</span></div>{rows.length?rows.map(item=>{const agency=Array.isArray(item.ap_agencies)?item.ap_agencies[0]:item.ap_agencies;return <Link href={`/owners/dashboard/placements/${item.id}`} key={item.id}><span className={`placement-state ${item.status}`}>{item.status.toUpperCase()}</span><div><b>{agency?.name??"Agency"}</b><small>{item.disclosure_label} · {item.placement_type}{item.placement_key?` / ${item.placement_key}`:""}</small></div><time>{new Date(item.starts_at).toLocaleDateString("en-PH")} — {new Date(item.ends_at).toLocaleDateString("en-PH")}</time><i>MANAGE →</i></Link>}):<div className="ops-empty"><strong>No placement records yet.</strong><span>Schedule the first disclosed commercial placement using the form above.</span></div>}</section></main></OwnerOperationsShell>}
