import Link from "next/link";
import { requireStaffRole } from "@/lib/auth/authorization";
import { OwnerOperationsShell } from "../_components/portal-shells";

export default async function ModerationQueue() {
  const { supabase, user } = await requireStaffRole(["super_admin", "moderator"]);
  const { data: agencies } = await supabase.from("ap_agencies").select("id,name,country,publication_status,submitted_at").in("publication_status", ["submitted", "approved"]).order("submitted_at", { ascending: true });
  return <OwnerOperationsShell active="moderation" email={user.email}><main className="ops-main"><header className="ops-header"><div><p className="ops-kicker">TRUST OPERATIONS</p><h1>Moderation queue.</h1><p>Review agency profiles for completeness and policy compliance. Approval and publication remain separate decisions.</p></div><div className="ops-summary"><span>PROFILES WAITING</span><strong>{agencies?.length ?? 0}</strong><small>Oldest submissions first</small></div></header><div className="ops-toolbar"><span>Profiles requiring an owner decision</span><Link href="/owners/dashboard">RETURN TO OVERVIEW</Link></div><section className="ops-grid">{agencies?.length ? agencies.map((agency) => <article className="ops-card" key={agency.id}><div className="ops-card-top"><span className="ops-badge">{agency.publication_status}</span><span className="ops-card-id">{agency.id.slice(0, 8)}</span></div><h2>{agency.name}</h2><p>{agency.country || "Country not provided"}</p><div className="ops-card-footer"><small>{agency.submitted_at ? new Date(agency.submitted_at).toLocaleDateString("en-PH") : "Submission date unavailable"}</small><Link className="ops-action" href={`/owners/dashboard/moderation/${agency.id}`}>REVIEW PROFILE →</Link></div></article>) : <div className="ops-empty"><strong>Moderation is clear.</strong><span>No agency profiles are currently awaiting approval or publication.</span></div>}</section></main></OwnerOperationsShell>;
}
